spring:
  application:
    name: carrental
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.1.199/carrental
    #jdbc:postgresql://localhost/carrental
    #jdbc:postgresql://91.246.64.81/carrental
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver